-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- I use this at work to prevent formatting all the nice work of my colleagues.
--  vim.g.autoformat = false
